---
- name: Configure MOTD
  block:
    - name: Ensure .config file exists
      file:
        path: "{{ target_dir }}/.config/neofetch"
        state: directory
    - name: Copy neofetch config
      copy:
        src: files/neofetch/config.conf
        dest: "{{ target_dir }}/.config/neofetch/"
    - name: Copy megacorplogo
      copy:
        src: files/neofetch/megacorplogo
        dest: "{{ target_dir }}/.config/neofetch/"
