---
- name: Install simple software without any additional configuration
  community.general.rpm_ostree_pkg:
    name: 
      - podman
      - htop
      - tldr
      - gcc
      - git
      - zsh
      - tmux
      - ripgrep
      - neovim
      - neofetch
    state: present
  when: ansible_facts['pkg_mgr'] == 'atomic_container'

- name: Install and configure zsh shell
  block:
    - name: Create .oh-my-zsh dir
      file:
        path: "{{ target_dir }}/.oh-my-zsh"
        state: directory
    - name: Make ohmyzsh git directory safe
      command: "git config --global --add safe.directory {{ target_dir }}/.oh-my-zsh"
      check_mode: no
    - name: Clone ohmyzsh repo
      git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: "{{ target_dir }}/.oh-my-zsh"
    - name: Copy zsh config to skel dir
      copy:
        src: files/zshrc/.zshrc
        dest: "{{ target_dir }}"
    - name: Copy bash_profile to skel dir
      copy:
        src: files/zshrc/.bash_profile
        dest: "{{ target_dir }}"

- name: Install and configure tmux
  block:
    - name: Make tmux git directory safe
      command: "git config --global --add safe.directory {{ target_dir }}/.tmux"
      check_mode: no
    - name: Download pretty tmux from git
      git:
        repo: "https://github.com/gpakosz/.tmux.git"
        dest: "{{ target_dir }}/.tmux"
    - name: Copy local tmux config to home dir
      command: cp .tmux/.tmux.conf.local .
      args:
        chdir: "{{ target_dir }}"
    - name: Create tmux config symlink
      command: ln -s -f .tmux/.tmux.conf
      args:
        chdir: "{{ target_dir }}"

- name: Install and configure nvim
  block:
    - name: Create .config dir in skel
      file:
        path: "{{ target_dir }}/.config"
        state: directory
    - name: Make nvim git directory safe
      command: "git config --global --add safe.directory {{ target_dir }}/.config/nvim"
      check_mode: no
    - name: Download nvchad from git
      git:
        repo: https://github.com/nvchad/nvchad
        depth: 1
        dest: "{{ target_dir }}/.config/nvim"

    - name: Create custom dir in nvim folder
      file:
        path: "{{ target_dir }}/.config/nvim/lua/custom"
        state: directory

    - name: Upload chadrc.lua file
      copy:
        src: files/nvim/chadrc.lua
        dest: "{{ target_dir }}/.config/nvim/lua/custom"

    - name: Upload plugins.lua file
      copy:
        src: files/nvim/plugins.lua
        dest: "{{ target_dir }}/.config/nvim/lua/custom"
