---
- name: Ubuntu latest packages update/upgrade and clean
  block:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Remove useless packages from the cache
      apt:
        autoclean: yes
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

- name: Update MOTD
  block:
    - name: Upload MOTD script
      copy:
        src: files/MOTD.sh
        dest: /usr/bin
    - name: Copy configuration script
      copy:
        src: files/update-MOTD.sh
        dest: /tmp
    - name: Make configuration script executable
      file:
        path: /tmp/update-MOTD.sh
        mode: '0744'
    - name: Run configuration script
      shell: /tmp/update-MOTD.sh
      
